version: '3.8'

services:
  postgres:
    container_name: vital-db
    image: postgres
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./src/db/sql/databases.sql:/docker-entrypoint-initdb.d/1.databases.sql
      - ./src/db/sql/schema.sql:/docker-entrypoint-initdb.d/2.schema.sql
      - ./src/db/sql/data.sql:/docker-entrypoint-initdb.d/3.data.sql
      - ./src/db/sql/indexes.sql:/docker-entrypoint-initdb.d/4.indexes.sql
