#
# Schemas
#

openapi: "3.0.3"

info:
  description: API for the Essential Mail Application
  version: 1.0.0
  title: Essential Mail Backend

servers:
  - url: http://localhost:3010

paths:
  /login:
    post:
      description: Login
      requestBody:
        description: Login Credentials
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/credentials"
      responses:
        200:
          description: Login Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user"
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
  
  /register:
    post:
      description: New Account
    
      responses:
        200:
          description: Account Created
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"

components:
  schemas:
    error:
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
      required:
        - code
        - message

    credentials:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      required:
        - email
        - password

    user:
      type: object
      properties:
        name:
          type: string
        token:
          type: string
        email:
          type: string
      required:
        - name
        - token
        - email
