#
# Schemas
#

openapi: "3.0.3"

info:
  description: API for the Essential Mail Application
  version: 1.0.0
  title: Essential Mail Backend

servers:
  - url: http://localhost:3010

paths:
  /login:
    post:
      description: Login
      requestBody:
        description: Login Credentials
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/credentials"
      responses:
        200:
          description: Login Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user"
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"

  /register:
    post:
      description: New Account
      requestBody:
        description: Register Credentials
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/registerInfo"
      responses:
        200:
          description: Account Created
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"

  /mailbox:
    get:
      description: Return User's Mailboxes
      security:
        - bearerAuth: []
      responses:
        200:
          description: Successful Return
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/mailboxes"
        401:
          description: Unauthorised Attempt
        404:
          description: Not Found
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"

  /mail:
    get:
      description: Return Mail from Specified Mailbox
      security:
        - bearerAuth: []
      parameters:
        - in: query
          description: Specified Mailbox
          name: mailbox
          required: true
          schema:
            type: string
      responses:
        200:
          description: Successful Return
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/mailbox"
        401:
          description: Unauthorised Attempt
        404:
          description: Not Found
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"

components:
  schemas:
    error:
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
      required:
        - code
        - message

    registerInfo:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
        password:
          type: string
      required:
        - username
        - email
        - password

    credentials:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      required:
        - email
        - password

    user:
      type: object
      properties:
        name:
          type: string
        token:
          type: string
        email:
          type: string
      additionalProperties: false
      required:
        - name
        - token
        - email

    mailboxes:
      type: array
      items:
        type: string

    mailbox:
      type: array
      items:
        $ref: "#/components/schemas/previewmail"

    previewmail:
      type: object
      properties:
        id:
          type: string
          format: uuid
        to:
          type: object
          properties:
            name:
              type: string
            email:
              type: string
        from:
          type: object
          properties:
            name:
              type: string
            email:
              type: string
        subject:
          type: string
        received:
          type: string
        seen:
          type: integer
        sent:
          type: string
        preview:
          type: string
      additionalProperties: false
      required:
        - id
        - to
        - from
        - seen
        - sent
        - subject
        - received
        - preview

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
