#
# Schemas
#

openapi: "3.0.3"

info:
  description: API for the Vital Mail Application
  version: 1.0.0
  title: Vital Mail Backend

servers:
  - url: http://localhost:3010

paths:
  /account:
    post:
      description: Change Account Details
      security:
        - bearerAuth: []
      requestBody:
        description: Changes to Enact
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/changes"
      responses:
        200:
          description: Changes were Successful
        401:
          description: Unauthorised Attempt
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
  /login:
    post:
      description: Login
      requestBody:
        description: Login Credentials
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/credentials"
      responses:
        200:
          description: Login Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user"
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"

  /register:
    post:
      description: New Account
      requestBody:
        description: Register Credentials
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/registerInfo"
      responses:
        200:
          description: Account Created
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"

  /mailbox:
    get:
      description: Return User's Mailboxes
      security:
        - bearerAuth: []
      responses:
        200:
          description: Successful Return
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/mailboxes"
        401:
          description: Unauthorised Attempt
        404:
          description: Not Found
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"

    post:
      description: Create a Custom Mailbox
      security:
        - bearerAuth: []
      requestBody:
        description: Name of the Mailbox
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/newbox"
      responses:
        201:
          description: Mailbox Created
        403:
          description: Name Taken
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"

    delete:
      description: Delete a Custom Mailbox
      security:
        - bearerAuth: []
      requestBody:
        description: Name of the Mailbox
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/newbox"
      responses:
        200:
          description: Successfully Deleted
        404:
          description: Mailbox does not exist
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"

  /mail:
    get:
      description: Return Mail from Specified Mailbox
      security:
        - bearerAuth: []
      parameters:
        - in: query
          description: Specified Mailbox
          name: mailbox
          required: true
          schema:
            type: string
      responses:
        200:
          description: Successful Return
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/mailbox"
        401:
          description: Unauthorised Attempt
        404:
          description: Not Found
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
    post:
      description: Send New Mail
      security:
        - bearerAuth: []
      requestBody:
        description: Content of email
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/newmail"
      responses:
        201:
          description: Mail Sent Successfully
        404:
          description: User does not exist
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
    put:
      description: Moves messages to specified box
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: mailbox
          description: Mailbox to move messages to
          required: true
          schema:
            type: string
      requestBody:
        description: List of Messages to Move
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/messageArray"
      responses:
        200:
          description: Email was moved to the same box
        404:
          description: Email not found
        409:
          description: Cannot move into sent mailbox
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"

    delete:
      description: Delete set of messages
      security:
        - bearerAuth: []
      requestBody:
        description: List of Messages to Delete
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/messageArray"
      responses:
        200:
          description: Messages were successfully deleted
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"

  /mail/{id}:
    get:
      description: Returns the desired email from the id
      security:
        - bearerAuth: []
      parameters:
        - name: id
          description: id of the email
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Successful Return
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/mail"
        404:
          description: Not Found
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"

components:
  schemas:
    error:
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
      additionalProperties: false
      required:
        - code
        - message

    registerInfo:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
        password:
          type: string
      additionalProperties: false
      required:
        - username
        - email
        - password

    credentials:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      additionalProperties: false
      required: [email, password]

    user:
      type: object
      properties:
        name:
          type: string
        token:
          type: string
        email:
          type: string
      additionalProperties: false
      required:
        - name
        - token
        - email

    mailboxes:
      type: array
      items:
        type: string

    messageArray:
      type: array
      items:
        type: string
        format: uuid

    mailbox:
      type: array
      items:
        $ref: "#/components/schemas/previewmail"

    mail:
      type: object
      properties:
        id:
          type: string
          format: uuid
        to:
          type: object
          properties:
            name:
              type: string
            email:
              type: string
          required:
            - name
            - email
          additionalProperties: false
        from:
          type: object
          properties:
            name:
              type: string
            email:
              type: string
          required:
            - name
            - email
          additionalProperties: false
        subject:
          type: string
        timestamp:
          type: string
        content:
          type: string
        seen:
          type: number
      additionalProperties: false
      required:
        - id
        - to
        - from
        - seen
        - subject
        - timestamp
        - content

    newmail:
      type: object
      properties:
        to:
          type: string
        subject:
          type: string
        content:
          type: string
      additionalProperties: false
      required:
        - to
        - subject
        - content

    newbox:
      type: object
      properties:
        boxName:
          type: string
      additionalProperties: false
      required:
        - boxName

    previewmail:
      type: object
      properties:
        id:
          type: string
          format: uuid
        to:
          type: object
          properties:
            name:
              type: string
            email:
              type: string
          required:
            - name
            - email
        from:
          type: object
          properties:
            name:
              type: string
            email:
              type: string
          required:
            - name
            - email
        subject:
          type: string
        seen:
          type: integer
        timestamp:
          type: string
        preview:
          type: string
      additionalProperties: false
      required:
        - id
        - to
        - from
        - seen
        - timestamp
        - subject
        - preview

    changes:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
      additionalProperties: false

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
